name: CD | Docker-Build-Release

on:
  # push:
  #   branches:
  #     - "main"
  # release:
  #   types: [published]
  workflow_dispatch:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - repository: justinwlin/mistral7b_openllm
            model: mistralai/Mistral-7B-Instruct-v0.2
            tag: latest
          # - repository: justinwlin/mixtral_8x7b_openllm
          #   model: mistralai/Mixtral-8x7B-v0.1
          #   tag: latest
          - repository: justinwlin/llama2_13b_openllm
            model: NousResearch/llama-2-13b-hf
            tag: latest
          # - repository: justinwlin/llama2_70b_openllm
          #   model: NousResearch/llama-2-70b-hf
          #   tag: latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Build and push Docker image
        run: depot build -t ${{ matrix.repository }}:${{ matrix.tag }} . --build-arg MODEL=${{ matrix.model }} --push --platform linux/amd64
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
